### ISSUE TITLE
set up codecov and appveyor

### ISSUE THREAD

**Issue by thevaachandereng** [gitter-lab/LPWC#20]
we should set up codecov and appveyor through gitter lab branch of LPWC. It is currently set up through my account.

**Comment by thevaachandereng** [comment]
Codecov is now set up through gitter-lab.

**Comment by agitter** [comment]
Let's reopen this until I set up AppVeyor through the organization or decide that it is not necessary.  I still haven't looked at the instructions in detail.

**Comment by agitter** [comment]
It looks like Daniel figured it out, but I still haven't tried it myself
