### ISSUE TITLE
shift error in run

### ISSUE THREAD

**Issue by thugib** [gitter-lab/LPWC#22]
I received an error: Error in shift[i] <- score(bcorr, lags) : replacement has a length zero.

The command was: LPWC::corr.bestlag(kmat, timepoints = timepoints)

The first 5 rows of the matrix kmat[] are :
kmat[1:5,]
              k2.5m       k5m      k10m      k15m      k20m       k30m        k1h        k3h        k6h        k9h       k12h       k15h       k18h
AT1G50040 0.6762992 0.6357176 0.0000000 0.0000000 0.0000000 -1.0994969 -0.7865366  0.0000000 -0.7189853  0.0000000  0.0000000  0.0000000  0.0000000
AT3G54720 0.4488114 0.0000000 0.3747782 0.6030834 0.5920215  0.5217524  0.0000000 -0.6376395 -0.5126850 -0.5436959 -0.6493731  0.0000000 -0.2869364
AT1G01010 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000  1.1150165  1.9223267  2.0520983  2.2537342  1.5281845  1.4821853  1.3771516
AT1G01030 0.0000000 0.0000000 0.7226280 0.6738165 0.4817093 -0.4557851  0.0000000  0.5577736  0.0000000 -0.7737706 -0.7789661 -0.4720915  0.0000000
AT1G01040 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000  0.0000000 -0.6924797  0.0000000  0.2577919  0.6346532  0.2693469  0.1988710  0.0000000
 k21h       k24h       k27h      k30h
AT1G50040 -0.8190957 -0.7514720 -0.8236975 0.0000000
AT3G54720 -0.3000221 -0.3970144 -0.2185353 0.0000000
AT1G01010  1.5380587  1.5610146  0.6812520 0.6232566
AT1G01030  0.0000000  0.0000000  0.0000000 0.0000000
AT1G01040  0.0000000  0.0000000  0.0000000 0.0000000

 Timepoints are: 
timepoints
 [1]  0.000  0.042  0.083  0.170  0.250  0.330  0.500  1.000  3.000  6.000  9.000 12.000 15.000 18.000 21.000 24.000 27.000 30.000

  After entering the command, it ran for a while. I left if to go overnight and found the error in the morning.

Matthew

**Comment by thevaachandereng** [comment]
Did you remove the gene variable in the first row and the first column with both character variable? Try running it for 5 genes and see if it works.

**Comment by thugib** [comment]
Thank you very much for the quick reply. 
I threw it the whole matrix. But if I take out the first column with the gene names then how will I be able to identify the rows ?
 str(kmat)
 num [1:20854, 1:17] 0.676 0.449 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:20854] "AT1G50040" "AT3G54720" "AT1G01010" "AT1G01030" ...
  ..$ : chr [1:17] "k2.5m" "k5m" "k10m" "k15m" ...

**Comment by agitter** [comment]
@thugib, thanks for pointing this out.  @thevaachandereng and I are discussing this and will get back to you soon.

**Comment by agitter** [comment]
@thevaachandereng that looks like a good solution to me.

I ran your code, and `as.dist` does what I expected it would with the row names.  What will happen in function `b` if the `data` variable does not have row names?

If we want to implement the new version, we could set up a few simple test cases to ensure it works under all scenarios we want to support.  That could include
- data matrix or data frame as input
- row names exist or are missing

In each case, we would call the function and confirm that the output is what we expect.

**Comment by thevaachandereng** [comment]
@agitter I am planning to use the code below which will only strip row names if there are row names. 

```
if(!is.null(row.names(data))){rownames <- row.names(data)}
```
