### ISSUE TITLE
Different correlation value generated from comp.corr() vs. comp.bestlag() with same input

### ISSUE THREAD

**Issue by leungi** [gitter-lab/LPWC#24]
Below is a sample dataset to illustrate the issue.

In the dataset, `b` lags `a` by 1 timestep, and `comp.bestlag()` picks this up, but `comp.corr()` doesn't seem to. As per documentation, `comp.corr()`  is supposed to pick the best lag and adjust the data for lags.

Look forward to your insights. 

``` r
library(LPWC)
library(dplyr)

# create data
a = c(0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4)
b = c(1, 2, 3, 3, 0, 1, 2, 3, 4, 0, 1, 1, 4, 4, 0, 1, 2, 3, 4, 0)

mydata <- data.frame(a = a, b = b) %>% t() %>% as.data.frame()

timepoints <- seq(ncol(mydata))

best.lag(as.matrix(mydata), timepoints, max.lag = NULL, C = 10)
#> [1] -1  1

comp.corr(as.matrix(mydata), matrix(rep(1:20), nrow = 2, ncol = 20, byrow = TRUE), 
  C = 10)
#>               1
#> 2 -4.500519e-18

corr.bestlag(as.matrix(mydata), max.lag = NULL, timepoints = timepoints, C = 10, 
  penalty = "high")
#> $corr
#>           1
#> 2 0.8682825
#> 
#> $lags
#> [1] -1  1
#> 
#> $C
#> [1] 10
```

**Comment by thevaachandereng** [comment]
If you briefly look at the corr.bestlag code, you can see that we in the comp.corr function we adjusted the timepoint with the best.lag output using the function prep.data. So, in this case since both (a & b) are lagged, you need to slide (a & b) before computing the correlation and the timepoints need to be lagged too.

**Comment by thevaachandereng** [comment]
Comp.corr does not pick the best lag, it only computes the correlation of the lagged entities with the lagged timepoints.

**Comment by leungi** [comment]
@thevaachandereng, thanks for prompt response.

I noticed the same behaviour as your example prior to posting, but raise the issue to confirm that `comp.corr()`, by design, doesn't find and apply best lag first prior to calculating correlation, as opposed to me understanding the documentation incorrectly :)

On a side note, when applying `corr.bestlag()` to multiple time series, what's the reference point for the output `$lags`?

From example below, do the `$lags` `c(-1, 1, -1,  0,  1, -1)` mean that a lag of 1 for `e` (i.e., 5th element) is the best lag to get the highest correlation with regards to `a` (i.e., the first element of the data frame fed into `corr.bestlag()`?

``` r
library(LPWC)
library(dplyr)

set.seed(4444)

# Normalized Cross-Correlation for lags from -4 to 4
a = c(0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4)
b = c(1, 2, 3, 3, 0, 1, 2, 3, 4, 0, 1, 1, 4, 4, 0, 1, 2, 3, 4, 0)
c = runif(20, 0, 4)
d = runif(20, 0, 4)
e = runif(20, 0, 4)
f = runif(20, 0, 4)

mydata <- data.frame(a = a, b = b, c = c, d = d, e = e, f = f) %>% t() %>% as.data.frame()

timepoints <- seq(ncol(mydata))

corr.bestlag(as.matrix(mydata), max.lag = NULL, timepoints = timepoints, C = 10, 
  penalty = "high")
#> $corr
#>              1            2            3            4            5
#> 2  0.868282540                                                    
#> 3 -0.018803908 -0.011000178                                       
#> 4  0.008501908  0.117496237  0.071772364                          
#> 5  0.070790541 -0.034910954  0.300295351  0.253153088             
#> 6  0.221699993  0.272978063 -0.109580124  0.339774411  0.085116494
#> 
#> $lags
#> [1] -1  1 -1 -1  1  1
#> 
#> $C
#> [1] 10
```

**Comment by thevaachandereng** [comment]
@leungi I think it was not your fault but the documentation might be slightly misleading. We will fix it soon. 

In corr.best lag with large multiple time series, we assume most entities would have a lag of 0 and a lag of 0 would be the reference point. However, you can create a dataset with an equal number of positive and negative lags with a small dataset and this affects the reference point. 

These are really good questions. Please let me know if that addresses the problem you had.  I'll close this issue in 1 week if there is no further discussion.

**Comment by agitter** [comment]
@leungi thanks for your additional comments in #25.  We merged that pull request, so I'll respond here instead.

> I look at each genes as a time series, and my understanding is that lags are computed by comparison of one time series to another. While I get the point that it's with respect to the original times, what confuses me is which gene (time series) is being used as reference. Is it the one with zero lag?

> 1. suppose we have 5 genes, all sharing 1 set of common timepoint
> 2. suppose bestlag() yields c(-1, 1, 0, 2, 0)
> 3. since we have 2 zero elements (i.e., 3rd and 5th), do those elements with non-zero lags (i.e., 1st, 2nd and 4th) lagged with reference to the 3rd or 5th element?

The lags are indeed calculated by examining gene-gene similarity.  However, the integer lags `c(-1, 1, 0, 2, 0)` are with respect to an absolute reference vector of timepoints, not any other particular gene.  Then to compute gene-gene similarity after fixing the best lags, the offsets for both genes are used.  At this time, we can get the relative offset between gene *i* and *j*.

This is pretty confusing, so we updated the vignette in #25.  Can you please see if the new figures in the `Interpreting lags` section are useful?  We explicitly show the original timepoints vector, how gene 1 and gene 2 are lagged with respect to that vector, and which expression values of gene 1 and gene 2 are aligned once we apply both lags.  One example shows a comparison of a gene with a -1 lag and another with a +1 lag, like your example above.  Here is the latest vignette:
[LPWC.pdf](https://github.com/gitter-lab/LPWC/files/2057962/LPWC.pdf)

**Comment by leungi** [comment]
@agitter, thanks for explanation and link to updated vignette. The illustrations under `Interpreting lags` is very useful, particularly for 2-genes case. 

However, I'm still unclear how multiple genes case is handled. Below is a 3-gene example, similar to the case shown in vignette, with an added gene with a `-2` lag to start

``` r
library(LPWC)
library(tidyverse)

# create data
b <- rbind(c(rep(0, 5), 8, 0), c(rep(0, 4), 4.3, 0, 0), c(rep(0, 2), 5, rep(0, 
  4))) + rnorm(3, 0, 0.5)

# # plot data 
# b %>% as.tibble() %>% mutate(gene = row_number()) %>%
# gather(key, value, -gene) %>% mutate(key = as.numeric(str_extract(key,
# '\\d+'))) %>% ggplot(aes(x = key, y = value, group = gene, color =
# as.factor(gene))) + geom_line()

# derive lags using timepoints set #1
best.lag(b, c(1, 2, 3, 4, 5, 6, 7), C = 10)
#> [1] -1  1  0

# using timepoints set #2
best.lag(b, c(0, 5, 15, 30, 45, 60, 75), C = 10)
#> [1] -1  1  1
```

Notes:

1. As in the 2-gene example in vignette, it's expected that lagging gene 1 by `-1` and lagging gene 2 by `1` should yield highest correlation, but the result for gene 3 is not intuitive.
2. `best.lag()` returns different values depending on magnitude of `timepoints`; is this intentional?


-

**Comment by thevaachandereng** [comment]
@leungi Most of the computation is done and stored for 2 genes. If you look at the correlation matrix, we store it for pair i and j. 
Also from the output you observe, we expect the best.lag and comp.corr to change depending on the timepoints provided.
