### ISSUE TITLE
Minor edit to example in `best.lag()` documentation

### ISSUE THREAD

**Issue by leungi** [gitter-lab/LPWC#26]
The following example is presented in the `best.lag()` documentation

```
#' @example best.lag(array(rnorm(20), c(5, 4)), timepoints = c(0, 5, 10,
#'          20, 40), C = 300)
```

I believe it should be:

```
#' @example best.lag(array(rnorm(20), c(4, 5)), timepoints = c(0, 5, 10,
#'          20, 40), C = 300)
```

**Comment by agitter** [comment]
Thanks for catching this @leungi.  We'll double-check the other examples too and fix this.

Can we acknowledge your contributions and feedback in our vignette?  If so, please let us know what name to use, or we can use `GitHub user leungi`.

**Comment by thevaachandereng** [comment]
@leungi Thank you for your feedback. We fixed it.

**Comment by agitter** [comment]
Closed by #27

**Comment by leungi** [comment]
@agitter, thanks for your consideration. If you wish, @leungi is fine.

**Comment by thevaachandereng** [comment]
Hi @leungi we would like to acknowledge you in our paper. Please let us know what name we can use for the acknowledgment.

**Comment by agitter** [comment]
We can also continue using `GitHub user leungi` if that is still your preference.

**Comment by leungi** [comment]
@thevaachandereng, @agitter: thanks for the inclusion; I feel so honoured for doing so little compared to y'all! 😅

If you may, please use Ivan Leung (ivan.yh.leung@gmail.com).
