### ISSUE TITLE
Do Zero-Count genes need to be filtered? 

### ISSUE THREAD

**Issue by JohnWSteill** [gitter-lab/LPWC#33]
Hi Tony and Thevaa,

> LPWC::corr.bestlag(my_data[49:58,], timepoints = timepoints, max.lag = 20, penalty = "high", iter = 10) 

... no problem, just like in the vignette

LPWC::corr.bestlag(my_data, timepoints = timepoints, max.lag = 20, penalty = "high", iter = 10)
**Error in lags[j] <- val[which.max(corr)] : replacement has length zero
In addition: Warning message:
In cor(data[i, ], data[j, ]) : the standard deviation is zero**

I assume this is because my file contains all 20k genes, many of which are likely zero always. I will filter these out soon and follow up. 

fwiw my entire script:

dataFile = 'Data/Sub_391_2_pool_22adb_hg19_SOX2_plus__foregut_endoderm__32a860ee85db9ac9/genes.no_mt.ec.tab'
my_data = read.table(dataFile, header=TRUE, row.names=1, sep = '\t')
my_data = my_data[,-ncol(my_data)] # Drop description
timepoints = 0:96
solution = LPWC::corr.bestlag(my_data, timepoints = timepoints, max.lag = 20, penalty = "high", iter = 10)
dist <- 1 - solution$corr
plot(hclust(dist))

**Comment by thevaachandereng** [comment]
As you mentioned, you need to filter the genes with all "0's". Since correlation(a, b) is inversely proportional to the variance of a and b, I am assuming that's the error. Another issue to note, we have not made the package to accept all types of data yet. So, if you include gene list in the first column, it will emit an error.

**Comment by agitter** [comment]
@JohnWSteill Thanks for the comment.  In our LPWC case studies, we filtered the gene list first and only clustered genes that are differentially expressed over time.  That would remove these 0s and many other genes.  LPWC uses modified correlation, so genes that do not change substantially but have random variation around some baseline over time can be correlated with more significant temporal patterns by chance.  That can distort the clustering.

You are also using longer time series than we tested with previously.  We want to support that, so please let us know if you encounter other problems.

@thevaachandereng We should leave this issue open until we provide more guidance on this use case.  We could more explicitly write in the documentation and vignette that 0s need to be removed.  Or we could remove them automatically and report to the user how many were filtered out.  What do you think?

**Comment by agitter** [comment]
We decided to make the following updates:
1. Add a `Filtering genes` section to the vignette explaining why LPWC expects genes to be filtered and that 0 variance genes must be removed.
2. Check whether any input genes have 0 variance and return a descriptive error if they do.
3. Add a test case for 0 variance genes.

**Comment by agitter** [comment]
My recollection is that when we last talked about it in person, we decided to return an error instead of removing them automatically.  We were concerned that users may not realize we had removed some genes.

@JohnWSteill would that behavior seem reasonable to you as a user?

**Comment by JohnWSteill** [comment]
Very reasonable. It makes sense that if the user wants to have a fancy "null-variance" cluster or something, they should have to handle the bookkeeping. 

A bonus might be "low variance" warning, in which var/mean is nonzero but likely to give spurious numbers, but that probably isn't too high a priority.

**Comment by thevaachandereng** [comment]
@JohnWSteill You can get small variance with small intensity, even though the log ratios are high. Maybe perhaps coefficient of variation (CV)?

**Comment by JohnWSteill** [comment]
This might be getting off topic, but it's a question I'm interested in (Perhaps better handled in a "vignette edits" issue? This seems close to being closed.) 

For my application, I have expression data for all 20k genes, and I'm looking for an "interesting" subset to feed to this algorithm. Filtering out the zero variance helps, but 12k is still too many to play with comfortably.

- My first filter was to take the highest variance genes, but that was equivalent to just taking the highest expressors, even if the relative change was small. 
- My second was to take the highest CV's, sd/mean, as you suggested Thevaa. But that just picked out the genes with smallest nonzero counts, and thus high, noisy fold changes. 
- My "goldilocks" solution was to pick the genes with the highest sd^2/mean. It seems to pick out the genes with non-noisy largish moves. But there's probably many functions with this balance, I have no argument that its the best one.

**Comment by agitter** [comment]
Good question.  I agree that we can keep this issue focused on the zero counts so that we can close it after adding informative error messages for genes with constant 0 expression.  I created #40 for the follow up discussion about filtering in general.
