### ISSUE TITLE
Precision issue

### ISSUE THREAD

**Issue by thevaachandereng** [gitter-lab/LPWC#48]
I am not sure if this is an issue. But this might affect the algorithm (floating point). I tried the code below with vector of size 8. 

```
wt.corr(1:8, 2:9, rep(0, 8))
wt.corr(1:8, 2:9, rep(1, 8))
```

One thing we can do is completely avoid weights with a weight of 0.

**Comment by agitter** [comment]
What is the problem with those lines?  Do they produce different outputs?

**Comment by thevaachandereng** [comment]
<img width="239" alt="screen shot 2018-08-16 at 11 48 24 am" src="https://user-images.githubusercontent.com/13036494/44222509-57f31380-a14a-11e8-85bc-59d8808795cf.png">

**Comment by thevaachandereng** [comment]
I understand they are pretty close but with hierarchical clustering, I think these things do change a cluster assignment.

**Comment by agitter** [comment]
Is this just a bug in the logic?  Should the `else if` in line 28 be an `if` that is independent from the `if` at 24?

https://github.com/gitter-lab/LPWC/blob/ca92dc3e70de7f5984e61d0289b648a6ce1f37c8/R/wt_corr.R#L23-L30

**Comment by thevaachandereng** [comment]
This is not an issue with the floating point.
