### ISSUE TITLE
fixing pkgdown issue

### ISSUE THREAD

**Issue by thevaachandereng** [gitter-lab/LPWC#53]
Without eval = TRUE in the devtools download, LPWC webpage does not run the vignette, however CRAN does not like it in the system.

**Comment by agitter** [comment]
We can make arbitrary modifications to the code or documentation before running `pkgdown::build_site()` in Travis CI.  Can we add a new line or a script here to prepare the package for pkgdown between lines 9 and 10?  A simple `sed` call may be sufficient.

https://github.com/gitter-lab/LPWC/blob/51d7d719cd9c5b71200b1ea5614b4d2d9d5e8a39/.travis.yml#L8-L10

For documentation, can you also please note here the specific `eval = TRUE` line that is a problem.

**Comment by thevaachandereng** [comment]
I am going to set `eval = FALSE` and try something.

**Comment by agitter** [comment]
As of 10c3b8895881cafd2a4056e440838ed41180feb5 the AppVeyor build is now failing.  We'll need to watch that as well or restart the build.

**Comment by agitter** [comment]
It must have been temporary.  The AppVeyor build passes again now.

**Comment by thevaachandereng** [comment]
Appveyor is really unstable. With my other package (bayesCT), it always fail. I have good faith on Travis usually. Did you see my release note? Let me know if you want to add something.


Thevaa

On Mar 12, 2019, at 2:29 PM, Anthony Gitter <notifications@github.com<mailto:notifications@github.com>> wrote:


It must have been temporary. The AppVeyor build passes again now.

**Comment by agitter** [comment]
The release note looked great.

**Comment by agitter** [comment]
Closed by 9baaacd30686c45a0165de7a8df9d349abb10e48
