### ISSUE TITLE
findC error

### ISSUE THREAD

**Issue by thevaachandereng** [gitter-lab/LPWC#57]
Issues with findC function. It does not find the C value for all the cases.

**Comment by agitter** [comment]
Can you please add an example that will reproduce the error?

**Comment by thevaachandereng** [comment]
<img width="478" alt="Screen Shot 2019-05-28 at 9 24 58 PM" src="https://user-images.githubusercontent.com/13036494/58481525-24402200-818f-11e9-9e05-7780e8508bfb.png">

**Comment by agitter** [comment]
When making a pull request to fix this issue, please start with a new test case that reproduces the error and fails.  Then we can confirm that the code fix solves the problem and it doesn't recurr.

Do you know the root cause?  What is provided as input to `uniroot` that causes it to fail?
