### ISSUE TITLE
error in shift [i]<- score (bcorr, lags): replacement has length zero

### ISSUE THREAD

**Issue by likainan001** [gitter-lab/LPWC#61]
Sorry for not seeing your reply in time.  I am using the corr.bestlag. The command is ：output.Low<- corr.bestlag (data=num. data, timepoints=c (0.0001,6, 12, 24, 48, 96, 120), max.lag=1, severity="low", iter=10), error in shift [i]<- score (bcorr, lags): replacement has length zero

**Comment by agitter** [comment]
Thanks for following up.  I reopened issue #60 so that we can continue discussing this problem there.
